name: Trigger AWS Lambda Function

on:
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Thay đổi thành khu vực của bạn nếu cần

      - name: Invoke AWS Lambda Function
        run: |
          FUNCTION_NAME="Stop_Ec2"  
          PAYLOAD='{"key1": "value1", "key2": "value2"}'  

          RESPONSE=$(aws lambda invoke \
            --function-name $FUNCTION_NAME \
            response.json \
            --query 'StatusCode' --output text)
